"""Add products relationship to Order

Revision ID: c3d9ce6ee27c
Revises: df4a07aeea13
Create Date: 2024-12-30 18:42:22.404907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d9ce6ee27c'
down_revision: Union[str, None] = 'df4a07aeea13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
